const { Mezcal } = require("../models");

const mezcalData = [
  {
    name: "Banhez Espadin & Barril",
    style: "Ensamble/Joven",
    agave: "Espadin & Barrill",
    abv: 42,
    origin: "Ejutla, Oaxaca",
    aroma: "Herbaceous, citrus fruit, and clay",
    pallet: "Baked banana, black pepper, and peat",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNBg7UqvEThHD6e1MrN31JcatbkyKoLsN5A1wO7?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Banhez Tobala",
    style: "Joven",
    agave: "Tobala",
    abv: 47,
    origin: "La Compania, Oaxaca",
    aroma: "Green mango, leather, and fresh green herbs",
    pallet: "Sweet tropical fruit, ripe pineapple, and banana",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPU4CixWJRkXbu7ycuY9WYPJJEdRzKP3-giqYRW?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Bozal Borrego",
    style: "Pechuga",
    agave: "Castilla",
    abv: 52,
    origin: "Ejutla, Oaxaca",
    aroma: "Lemon zest, smoked lean lamb, fruity",
    pallet: "Pine, allspice, sea salt, and galla apple",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNT4UQ878HVoxjSXcYb5KpBKJaLteNPT3Ug2GUB?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Bozal Chino Verde",
    style: "Joven",
    agave: "Verde",
    abv: 48.4,
    origin: "Sierra Madre del Sur Mountains, Sola de Vega, Oaxaca",
    aroma: "Earth, dried herbs, burlap, soft smokiness",
    pallet: "Ancho chiles, charred meats",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPN-1TyjAUtivCFoJQe_vq1uIeOKPhNLgMxifWS?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Bozal Cuixe",
    style: "Joven",
    agave: "Cuishe",
    abv: 47,
    origin: "San Luis Amatlan, Oaxaca",
    aroma: "Citrus, strong minerality",
    pallet: "Dry, rich tropical fruit",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNeXM3S5dhC-nKoKkDfdNm9ztaFggQmTuJ3-ajd?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Bozal Sacatoro",
    style: "Joven",
    agave: "Sacatoro",
    abv: 44.8,
    origin: "Mazatlan, Oaxaca",
    aroma: "Wet earth, rich smokiness, wild flowers",
    pallet: "Herbal, minerality, salty, smooth",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMGAiAvYFvz1507kwDVF1RMZrCL80UKWw-cMQhe?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Bozal Tobasiche",
    style: "Joven",
    agave: "Tobaziche",
    abv: 47,
    origin: "Ejutla, Oaxaca",
    aroma: "Herbaceous, cedar",
    pallet: "Rich earth, savory smokiness",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipN7Mf9STGLiciGoigEo9bqBq1XpPC59Y3Q8cYxW?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Bruxo #2",
    style: "abocado, Ensamble",
    agave: "Espadin, Barril",
    abv: 46,
    origin: "Agua del Espino, Oaxaca",
    aroma: "Earthy, hints of citrus",
    pallet: "Brazil nuts, aloe",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMzN5eLo_c9KRvWdcTF9xDb5W95_dim_Jlv61ie?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Caballito Cerreo Chato",
    style: "Joven",
    agave: "Chato",
    abv: 46,
    origin: "Amatitan, Jalisco",
    aroma: "Cooked agave, baked bread, broiled grapefruit",
    pallet: "Green bell pepper, anise, cooked agave, cream, tangerine, vanilla",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNhfeWwea4LLvxE5F5V3D9_LtmolUzoXcRrORVT?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Chacolo 3 Anos Capon",
    style: "Joven",
    agave: "A. Angustifolia",
    abv: 48.3,
    origin: "Zapotitlan de Vadillo, Jalisco",
    aroma: "Mint, pine wood, lime",
    pallet: "Vanilla bean, peppermint, hint of lime, ginger",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMRwoHxqBAZe979d-rqTgPp4sn-gVwroQ-_rQjE?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Cuentacuentos El Barro",
    style: "Joven",
    agave: "Espadin",
    abv: 46,
    origin: "Santiago Matalan, Oaxaca",
    aroma: "Wet clay, green forest after rain, dark fruits",
    pallet:
      "Balanced with a sour touch, green apple, fresh cream, strawberry jam, brulee, coffee powder",
      image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipP_JDSjh1_JgCpsH2G5_srWg2eK51Zj4zI0_aFz?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Arroqueño",
    style: "Joven",
    agave: "Arroqueño",
    abv: 49,
    origin: "Santa Catarina Minas, Oaxaca",
    aroma: "Dark fruits (mostly cherry), clay, bright, vegetal",
    pallet: "Melon, baking chocolate, fresh green beans",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPubnrkmrA1d1fmU7Y5RmLTFSxIuF9TTGut_8KW?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Chichicapa",
    style: "Joven",
    agave: "Espadin",
    abv: 46,
    origin: "San Baltazar Chichicapa, Oaxaca",
    aroma: "Herbaceous, citrus, light smoke",
    pallet: "Smooth, fruity, tropical fruits, roasted agave",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipO6SYET8kbSIyYXh8yKBQ3hPNO4Mj8iV0r7rP13?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Magury Crema de Mezcal",
    style: "Joven",
    agave: "Espadin",
    abv: 40,
    origin: "San Luis del Rio, Oaxaca",
    aroma: "Sweet, smoky, chocolate, coffee",
    pallet: "Rich, creamy, balanced sweetness with smoky undertones",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMD3fslLC0HXecnXJqxsyWaZ6KxfDekBrRoKQX9?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Minero",
    style: "Joven",
    agave: "Espadin",
    abv: 46,
    origin: "Santa Catarina Minas, Oaxaca",
    aroma: "Sweet, fruity, earthy, smokey",
    pallet: "Smooth, complex, tropical fruits, roasted agave, chocolate",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMtIyT1go4IRNeargo1qlKw8gCNQiYDE6LWkg6_?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Pechuga",
    style: "Pechuga",
    agave: "Espadin",
    abv: 46,
    origin: "Santa Catarina Minas, Oaxaca",
    aroma: "Basil, lemon, ocean, fruit",
    pallet: "Smoky, warm, coal and spice",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOFLROGFfviYT7Fq80nITy1UxXjNq90LoGONiRG?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey San Pablo Ameyaltepec",
    style: "Joven",
    agave: "Pizorra, Tobala",
    abv: 47,
    origin: "Puebla",
    aroma: "Dried pineapple and papaya",
    pallet: "Very floral, dried tropical fruit, creamy cheese",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOKUX1eS1KGj7_-5SUeF9aeFhv10TRDXHLEChgF?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Santo Domingo Albarradas",
    style: "Joven",
    agave: "Espadin",
    abv: 48,
    origin: "Oaxaca",
    aroma: "Peaches, cream, sweet fruit",
    pallet: "Spicy, woody, clean dry finish",
    image: 'https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipO6KQc555MKovipshko-lytdWr2a09yx0Cj9ASk?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB',
  },
  {
    name: "Del Maguey Tepextate",
    style: "Joven",
    agave: "Tepextate",
    abv: 45,
    origin: "Santa Maria Albarradas, Oaxaca",
    aroma: "Complex, earthy, hints of smoke",
    pallet: "Delicate, roasted agave, herbal undertones, touch of sweetness",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMeKLbvnsmItq1GMe2zEK9C70Glzo5DrAke8epe?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Tobala",
    style: "Joven",
    agave: "Tobala",
    abv: 46,
    origin: "Santa Maria Albarradas, Oaxaca",
    aroma: "Intense, floral, tropical fruits",
    pallet: "Complez, tipe agave, sweet spices, touch of minerality",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMEkQKsQZl4JyHfssLBipi2NwIIyUgxX1MWqtbT?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Tobaziche",
    style: "Joven",
    agave: "Tobasiche",
    abv: 47,
    origin: "San Luis del Rio, Oaxaca",
    aroma: "Complex, herbal, hintes of smoke",
    pallet: "Vibrant, fresh agave, herbal undertones, subtle spiciness",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPgeEI1KSjXprzbyEr9WbxFIOQ_C8iqWNr9r4HZ?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Vida",
    style: "Joven",
    agave: "Espadin",
    abv: 42,
    origin: "San Luis del Rio, Oaxaca",
    aroma: "fruity aromatics, hints of honey, vanilla, roasted agave",
    pallet:
      "Ginger, cinnamon, burnt sandalwood, banana, tangerine, long soft finish",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMOwI6H1-AK7C_HzKLVJZczDUAYt4iIfiW7qCyL?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Vida de Muertos",
    style: "Joven",
    agave: "Espadin",
    abv: 45,
    origin: "San Luis del Rio, Oaxaca",
    aroma: "Tropical fruits, warming spices",
    pallet:
      "Creamy texture, floral notes, green herbs, poblano peppers, long complex finish",
      image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMNsHsAzhNdChgvI9qZ2T5Y9sIXLoiwWgKCyCfR?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Del Maguey Vida Single Village Puebla",
    style: "Joven",
    agave: "Espadin",
    abv: 40,
    origin: "Axocopan, Puebla",
    aroma:
      "Bright fruits and florals, hints of green herbs, poblano, minerality",
    pallet: "Agave, citrus, white peach, candied pine",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipP1mrObk_tsS5UepkkIoiDNmNeAU_v_vxAbLx-6?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "El Jolgorio Barril",
    style: "Joven",
    agave: "Barril",
    abv: 47,
    origin: "La Campana, Santa Maria, Zouquitlan, Oaxaca",
    aroma: "Earthy, light hints of smoke",
    pallet: "Delicate blend of sweetness, citrus and minerality",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipO_egS5X5vZVWk9sNHCfTTafTcv_YHq6f4NeNf_?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "El Jolgorio Cuixe",
    style: "Joven",
    agave: "Cuishe",
    abv: 47,
    origin: "Santa Maria, Santiago Matalan, Oaxaca",
    aroma: "Earthy, wet clay",
    pallet: "Spithy with subtle hints of smooth smoke",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOaMHUuOYxjF7GAEk2oklib9hife3TOjwGUztsq?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "El Jolgorio Espadin",
    style: "Aged in Glass",
    agave: "Espadin",
    abv: 47,
    origin:
      "Lachigui, San Luis del Rio, San Pedro Quiatoni, Santa Maria Zoquitlan, Santiago Matatlán",
    aroma: "Herbaceous, roasted agave, mint",
    pallet:
      "Savory with notes of citrus, basil, and rosemary. Warm lingering finish",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPduwwR4a5YA4YuSAA_Y_wt5GUdqWpX_WUSORAs?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "El Jolgorio Madrecuize",
    style: "Joven",
    agave: "Madrecuixe",
    abv: 46,
    origin: "Lachigui, reo Seco, Santa Maria, Zoquitlan, Santiago Matalan",
    aroma:
      "Herbal, floral notes, hints of fresh-cut grass with a touch of earthiness",
    pallet:
      "Complez and balanced, flavors of mints, eucalyptus, green vegetables, subtle hints of citrus",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMetXJtxxCI4FTckJDlag8V3ideNeo2xx6KJV2V?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "El Jolgorio Pechuga",
    style: "Pechuga",
    agave: "Espadin",
    abv: 46,
    origin: "Santa Maria Zoquitlan, Santiago, Matalan, Oaxaca",
    aroma: "Ripe fruits, spices, delicate smoke",
    pallet: "Sweet and savory flavors, tropical fruits, cinnamon, clove, umami",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNRDxwoHc-jszt3oj8s0Oom1F3-Iu0Nf2x_XHof?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "El Jolgorio Tepeztate",
    style: "Joven",
    agave: "Tepeztate",
    abv: 46,
    origin:
      "Lachigui, Rio seco, San Baltazar Guelavila, San Luis del Rio, Santa Maria Zoquitlan, Oaxaca",
    aroma:
      "Herbal and floral notes, hints of roasted agave and a touch of smoke",
    pallet: "Green pepper, tropical fruit, earthiness and a hint of minerality",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipN0Bn6FBnBkFr49HjZR5HzI6GUJDyhpAWiufhaT?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "El Jolgorio Tobala",
    style: "Joven",
    agave: "Tobala",
    abv: 47,
    origin: "Lachigui, San Baltazar, Guelavila, Santiago Matatlan, Oaxaca",
    aroma: "Banana, pine, lemon zest",
    pallet: "Brine, taffy, cedar, mango, pleasantly viscous",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNZeXZ1fqIHKSBp9G85uXW47ko1lZutmPipkHAM?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Fidencio Joven Clasico",
    style: "Joven",
    agave: "Espadin",
    abv: 45,
    origin: "Santiago Matalan, Oaxaca",
    aroma: "Wood smoke, green pepper, vegetal",
    pallet: "Tobacco, tar, pine",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOWKmONJsk0h3GHs_PaRfTddFaJ3vdPBeoDvV6B?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Gracias a Dios Espadin Reposado",
    style: "Reposado",
    agave: "Espadin",
    abv: 45,
    origin: "Santiago Matalan, Oaxaca",
    aroma: "Spicy, nutty, vanilla",
    pallet: "Low acidity/alcohol perception",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNboF85h_CmOmCyxHzXq8Ls8W8tQTtLYwy0YTnM?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Ilegal Joven",
    style: "Joven",
    agave: "Espadin",
    abv: 40,
    origin: "Matatlan Valley, Oaxaca",
    aroma: "Eucalyptus, minerals",
    pallet: "Green apple, fresh citrus, red chiltepes",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMEUFs959Hkks1wcPaKd_oj5NhZlOUxp5LljjDt?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Ilegal Reposado",
    style: "Reposado",
    agave: "Espadin",
    abv: 40,
    origin: "Matatlan Valley, Oaxaca",
    aroma: "Caramelized pear, bitter orange",
    pallet: "Clove, butterscotch, hints of vanilla",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNxjbfQ3IoeQ8Szm_JMl4DWugxTK_ZDYE-qo1yU?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Ilegal Anejo",
    style: "Anejo",
    agave: "Espadin",
    abv: 40,
    origin: "Matatlan Valley, Oaxaca",
    aroma: "Maple, clove, bitter orange",
    pallet: "Dark chocolate, sweet agave",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNSDS261GZFuAVmusb8CdMhq6gc_v7XXvTb0_48?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Ilegal 7 Year Anejo",
    style: "Extra Anejo",
    agave: "Espadin",
    abv: 41.32,
    origin: "Tlacolula, Oaxaca",
    aroma: "Roasted agave, baked apple, oak",
    pallet: "Honey, dark chocolate, fig",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNFR5yDBBc7egYnGnTDSDJqTlz2-5XDa5RSxlty?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Koch el Mezcal Joven",
    style: "Joven",
    agave: "Espadin",
    abv: 47,
    origin: "Rio de Ejutla, San Baltazar Guelavila, Oaxaca",
    aroma: "Herbaceous, ripe fruit",
    pallet: "Coconut, herbs, spices",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPOzAoKQ_YXswVSpDoupxmLuXWuZf__M760zkPL?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Higuera",
    style: "Joven",
    agave: "Dasylirion, Wheeleri",
    abv: 48,
    origin: "Chihuahua",
    aroma: "Herbal, hint of smoke, rosy, soft vanilla",
    pallet: "Herbs, pineapple, cinnamon candy, honey roasted peanuts",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNxzoNWDPhBqYXRcVACfQMpWCPhMCx7Kv7ykpi3?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Luna Bruto",
    style: "Joven",
    agave: "Bruto",
    abv: 50.62,
    origin: "Michoacan",
    aroma: "Light smoke, roasted papaya, old leather",
    pallet: "Mild roasted coconut, fermented vegetables, thyme, oregano",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOIUAZtS1lVSDzfWahlmxF-Mhz_l0sLlN5WaDwZ?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Luna Cupreata",
    style: "Joven",
    agave: "Cupreata",
    abv: 49,
    origin: "Etucuaro, Michoacan",
    aroma: "Bright and floral",
    pallet: "Subtle smoke, citrusy, smooth",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPi0NKuuxYTKvrqZz3F_nJO6dK8H-UdT_zXLXkV?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Luna Espadincillo",
    style: "Joven",
    agave: "Espadincillo",
    abv: 48,
    origin: "Etucuaro, Michoacan",
    aroma: "Citrus, grapefruit peel, strawberry yogurt",
    pallet:
      "Roasted agave, citrusy, layered with a touch of smoke, sweet and crisp finish",
      image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNy4cFkdwgmBErzxtbf364GvWKFk_Qti6-5xIYi?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Luna Manso Sahuayo",
    style: "Joven",
    agave: "Unspecified Sahuayo",
    abv: 48,
    origin: "Etucuaro, Michoacan",
    aroma: "Earthy, cheese, woodsy, agave, vanilla, sweet fruit",
    pallet: "Cigar leaf, chocolate, citrus, white pepper, hints of smoke",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNW30WIJbhgFgeWUEqwX3Pw-jrKAlSU0rFTR1ha?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Luna Reyes Chino",
    style: "Pechuga",
    agave: "Chino",
    abv: 48.51,
    origin: "Morelia, Michoacan",
    aroma: "Soft and grassy, citrus undertones",
    pallet: "Mint, fennel, lemongrass",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipN3hNQv4hWuH7ToTBRVdYEJ6oajn5uskgFpvyqX?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Venenosa Raicilla Sierra de Occidental",
    style: "Joven",
    agave: "Maximilians",
    abv: 42,
    origin: "Mascota, Jalisco",
    aroma: "Lime zest, acetone, savory herbs, terracotta",
    pallet:
      "Unsweetened lemon and lime juice, minerals, fresh ground pepper, followed by apple cider vinegar",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNmXK5DPrqT1a_N_tiAh1x0VjNxISnLZHSPuT9W?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Venenosa Raicilla Tabernas",
    style: "Joven",
    agave: "Chico Aguilar",
    abv: 46,
    origin: "Jalisco",
    aroma: "Grapefruit, grape skins",
    pallet: "Sugary canilla that falls quickly, agave nectar, cheese",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipM7jOmtdhgWRT0FLiPXb7Shs8ERYzVbpxrt_3Z1?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "La Venenosa Sierra de Tigre",
    style: "Joven",
    agave: "Bruto",
    abv: 44.8,
    origin: "Manzanilla de la Paz, Jalisco",
    aroma: "Fruity, apricots, oranges, sour",
    pallet: "Light fruit, salt, cinnamon, funky",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipP18ectrfziO5sgmdD6lNBXuLYUcwl3prWZk0TL?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcal Vago Espadin",
    style: "Joven",
    agave: "Espadin",
    abv: 50,
    origin: "Candelaria Yegole, Oaxaca",
    aroma: "Lilac, perfume, lavender",
    pallet: "Hot, mesquite and pine",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMMitcVuqPtPW9Dv_YKbu-IG-4Q4h6MFBwebs2v?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcal Vago Elote",
    style: "Joven",
    agave: "Angustifolia",
    abv: 50,
    origin: "Candelaria Yegole, Oaxaca",
    aroma: "Sweet notes, mint, candle wax",
    pallet: "Roasted sweet corn, caramel, cream",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPHgwCTl7hdJ67JAnQD0oYbXhGM6O-M34a0yGXN?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcal Vago Ensamble",
    style: "Ensamble",
    agave: "Barril, Coyote, Espadin, Sierra Negra, Tepeztate, Tobala",
    abv: 50,
    origin: "Sola de Vega, Oaxaca",
    aroma: "Clay, earthy, pine needles",
    pallet: "Charred sinnamon, pumpkin, chestnuts",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMFkLMOJibKp8tiUfMhCwseCgqB6CpXMIiPI2Qa?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcal Vago Madrecuixe",
    style: "Joven",
    agave: "Madrecuishe",
    abv: 50,
    origin: "Miahuatlan, Oaxaca",
    aroma: "Floral, earthy, fruity",
    pallet: "Minerals, orange, pepper",
  },
  {
    name: "Mezcales de Leyenda Guerrero",
    style: "Joven",
    agave: "Ancho",
    abv: 46,
    origin: "Mazatlan, Xochipala",
    aroma: "Citrus fruit, herbs, cheesy",
    pallet: "Citrus, papaya, black pepper",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOFQZ3D917aAFISJDe3y5V06Wo4YMKeqR9Vm_tJ?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcales de Leyenda Durango Cenizo",
    style: "Joven",
    agave: "Cenizo",
    abv: 47,
    origin: "Durango",
    aroma: "Floral, leather, wet clay, very light smoke",
    pallet:
      "Buttery, notes of coriander and fruit, finish is smooth and lingering like hard candy",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNDX5vi8njaT2puDYT5RFDjGc34d8N1c3jWetmC?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcales de Leyenda Montana",
    style: "Joven",
    agave: "Montana",
    abv: 45,
    origin: "Tamaulipas",
    aroma:
      "Deep char, herbal (spearmint, earth, minerals, overall greeness), damp forrest",
    pallet:
      "Sweet mild palate, powerful and very long finish with sweet menthol",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipP7JmRl_E7deBHWRFfiI0CvaI7LOr0SpDoWdBkN?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcales de Leyenda Puebla",
    style: "Joven",
    agave: "Tobala",
    abv: 48,
    origin: "San Nicolas Huajuapan, Puebla",
    aroma: "Green, herby, mineral, various underripe fruits, slight saltiness",
    pallet:
      "Fruity up front with an almost brininess and spiciness on the finish",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNVtQE2B0IROk2tRee1JHiYnPSm69LcuEov0UYr?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcales de Leyenda Potosi",
    style: "Joven",
    agave: "Salmiana",
    abv: 42,
    origin: "San Luis Potosi",
    aroma: "Smoky, floral, pepper",
    pallet: "Mild notes of elderflower, jalapeno, lemon",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipND53g0Ws1klm344Lu_IxDmq_s8NjuBjAxdhdBz?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcales de Leyenda Solar",
    style: "Joven",
    agave: "Cenizo, Durangensis",
    abv: 45.9,
    origin: "Durango",
    aroma: "Herbal notes",
    pallet: "Lingers on palate, clean",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipNZcmR2mw_-8W_N-YCptrMIhT7tcnojRKYORfpB?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mezcalosfera Madrecuixe y Verde",
    style: "Joven, Ensamble",
    agave: "Madrecuixe, Verde",
    abv: 48.29,
    origin: "Miahuatlan",
    aroma: "Nutty, leather, spice",
    pallet: "Mildly sweet, lemon, lavender, mango, spicy finish",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOSHj-jFBrBeCfPj7ptLg_aK9OI8s-PsXjWmaDZ?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Mina Real Joven",
    style: "Joven",
    agave: "Espadin",
    abv: 45,
    origin: "Santa Catarina Minas, Oaxaca",
    aroma: "Smoky agave, roasted pineapple, tropical fruit, earthiness",
    pallet: "Citrus, tropical fruits, herbal undertones",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOhA00Bqx26jCBeHMGu0V1sNPU4g_mPVfqQWasS?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Montelobos Joven",
    style: "Joven",
    agave: "Espadin",
    abv: 43,
    origin: "Oaxaca",
    aroma: "Grilled pineapple, citrus zest, hints of herbs and smokiness",
    pallet: "Citrus, pepper, hot",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipP7mEYRdZbOJ_A_c4brbHKOxp-wA1nSbipRHPFE?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Nuestra Soledad Ejutla",
    style: "Joven",
    agave: "Espadin",
    abv: 47,
    origin: "Ejutla de Crespo, Oaxaca",
    aroma: "Roasted fruits, herbs, earthiness, subtle citrus",
    pallet:
      "Fruity sweetness, hints of herbs and botanicals, pomelo, almond oil",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipO3fX4H8n257xt0HDTPMGm-e0X-_OiWecvuSn5Z?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Nuestra Soledad San Baltazar",
    style: "Joven",
    agave: "Espadin",
    abv: 48,
    origin: "Village of Tlacolula, San Luis del Rio, Oaxaca",
    aroma:
      "Chinese five spices (star anise, sloces, cinnamon, sichuan peppercorns, and fennel seed), wet stone",
    pallet: "Sweet, ripe, tropical fruits, caramelized agave",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMFLBzOW5bD3lbHZk7UdlGVXisAIDHJMmCzkSvC?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Nuestra Soledad San Luis Del Rio",
    style: "Joven",
    agave: "Espadin",
    abv: 48,
    origin: "Village of Tlacolula, San Luis del Rio, Oaxaca",
    aroma: "Orange, citrus, vanilla, mild/clean smoke",
    pallet:
      "Sparkling grapefruit and citrus aromatics with wet stone, rish and creamy mouth feel. Savory butterscotch and herbs.",
      image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipN9GTQJSC0TCs95gV_xxGbWeUAla6BLVQzcNVlY?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Nuestra Soledad Zoquitlan",
    style: "Joven",
    agave: "Espadin",
    abv: 46,
    origin: "Santa Maria, Zoquitlan, Oaxaca",
    aroma: "Smokey, tropical fruits, citrus",
    pallet:
      "Lemon zest, red pepper, berries, tropical fruits, quick finish that smooths out to leave a lingering sweetness",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOauk_QSEXqCNJ2PA41EITw6ahLZsPh82ZcuQft?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Ojo de Tigre",
    style: "Joven",
    agave: "Espadin, Tobala",
    abv: 40,
    origin: "Puebla, Oaxaca",
    aroma: "Honey, brown sugar",
    pallet: "Lime peel, white pepper, stone fruit",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMKmnVMHmC6s_huGVyDYOacxck_nTO_0CltFgn6?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Pierde Almas La Puritita",
    style: "Joven",
    agave: "Espadin",
    abv: 40,
    origin: "San Luis del Rio, Oaxaca",
    aroma: "Soft smoke, floral, subtle leather",
    pallet: "Savory smoke, earthy undertones, chocolate aftertaste",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPSjrM9Myk-UUf0lr0WC6BbXt2s-6LjVISF58nZ?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Peloton Joven",
    style: "Joven",
    agave: "Espadin",
    abv: 41,
    origin: "Oaxaca",
    aroma: "Kiwi fruit, lemon zest, dried peppercorn",
    pallet: "Soft smoke, hot spice, woody",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipMOUmT6ogSE213MCOD_Ofz7DYYahOjPduCc1An1?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Por Siempre",
    style: "Joven",
    agave: "Sotol",
    abv: 45,
    origin: "Janos, Chihuahua",
    aroma: "Earthy, rich wet soil, crystalized honey",
    pallet: "Black pepper, earth, spice, mineral",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipP_h-GkxNYNS_BMX9cy9ZiZvyKDn0J5CUYkPnbW?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Real Minero Barril",
    style: "Joven",
    agave: "Barril",
    abv: 50,
    origin: "Santa Catarina Minas, Oaxaca",
    aroma: "Wet rock, brown sugar, black pepper",
    pallet: "Spicy, earthy, tropical fruit, vanilla",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipO1L8zQ4XYF0mtJ5530nyDaH9bcxjqj9fENdUr4?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Rey Campero Espadin",
    style: "Joven",
    agave: "Espadin",
    abv: 48,
    origin: "Canelaria Yegole, Oaxaca",
    aroma: "Charred pineapple, anise, fennel",
    pallet: "Barbacoa, guava, mint, mineral, tamarind",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipN8g8dSqEc5ImqyZhdopeJDlj8FrMVprXcMFGNd?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Rey Campero Jabali",
    style: "Joven",
    agave: "Jabali",
    abv: 48,
    origin: "Oaxaca",
    aroma:
      "Bright and mineral with leathery smoke. Stone fruit, mostly peach. Lime peel.",
    pallet:
      "Great tension between smoke and fruit. Lots of sour fruit. Calamansi orange, green banana, lime juice, with powerful earthy smoke.",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOFm8TwAUHVoh4Ellqom-K8qluBGTWhTJ3Dhiu5?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Rey Campero Tepextate",
    style: "Joven",
    agave: "Tepeztate",
    abv: 48,
    origin: "Oaxaca",
    aroma: "Green bell pepper, jalapeno, light hint of mint",
    pallet:
      "Roasted jalapenos with a gentle spiciness. Hot tabales candy. Leather and ash in the finish",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipPnPh8EgoQZb7korAFPX3Vf_98786pQdEvkPCMw?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
  {
    name: "Xicaru Pechuga Mole",
    style: "Pechuga",
    agave: "Espadin",
    abv: 46,
    origin: "Santiago, Matatlan, Oaxaca",
    aroma: "Chicken fat, cedarwood, spice",
    pallet: "Chicken bullion, savory, salty, nutty",
    image: "https://photos.google.com/share/AF1QipMz5sG4_j0Z7W7T30hLXB0gCMWRwYxw1Yz4w22Dw9JCbluo3EstAeuvlU8SF4sNLw/photo/AF1QipOAws6Oi7wkz9tzuGi1M3iv72OgNDiqro3TrGnb?key=VHN5NExxQV91QmRiMXdkWmFNVDg3U2tkcmxMUUJB",
  },
];

const seedMezcals = () => Mezcal.bulkCreate(mezcalData);

module.exports = seedMezcals;
