const Tequila = require("../models/Tequila");

const tequilaData = [
  {
    brand: "Tequila Arette",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 38,
    aroma: "Baked agave, lemongrass, fresh herbs",
    pallet: "Lemon, wine, herbaceous, vanilla",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8WJXgOZ3FfuJg4GrqH0ReQ7sUtUkwgIqLWivwEqJFsagbyWW5wdRkb928bL_P1ZFxc9nX3CwmfAiJ9I4DLhnWYCN93CL1mN4GOyrPC2N8HvxINW8Hx5E0DAy8bPIMKkWV_ZN0uzOJTaI6weAqOK9de=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Tequila Arette",
    name: "Artesenal",
    origin: "Tequila, Jalisco",
    style: "Blanco",
    abv: 40,
    aroma: "Herbal, citrus, vegetal, spice",
    pallet: "Spice, pepper, minerals, vegetables",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8MF_INIamVNb9K0UCxBXwDp1gT_dfyVXxQhQTYd9MLc-L6BkL9FlireJXTmmWm7XNXwwGq4wW-UoX3whg_l9N3GOzMQexHLwLbz87gCxcWW2E0FHDqlaosV8DPmUygdBZ3bM9OyLJDuWWUCRtqd7Iv=w300-h600-s-no?authuser=0",
  },
  {
    brand: "Altos",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Vanilla, wood",
    pallet: "Citrus, oak, cinnamon, black pepper",
    appearance: "Gold",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9nj1LUphL-N5Tdz8YbDt8ZcfyE908NQ7hHY4UX_NtC8y9NE-8U-OObJxhPPPxdK29RiHL8N_Y0XRy9WGK7JmbVSCIdabPgClDRZbETH0miAe664NGqiAQf5OWTuIUmd6uA5DRJpwnB9mu1Yw5weV-P=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Atanasio",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 38,
    aroma: "Cooked and green agave, mint, basil, green apple",
    pallet:
      "Cooked agave, vanilla, tropical fruit, cracked pepper, vegetal notes",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-wKAfeCcOh1fYLKpFXSmj_J7_wOPmN3Mw-ctoQP8LNd2lTfElRnntu8KeuuglFu0SPRGh8QsT1j7ebEpJ4-WNiItQ5UCko2TznEA_6W2Eq0KRq4xMi54pSLbhqoOApaNHyU6_Z-z1eStJ26Pvp9sIV=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Avion",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Roasted agave, vanilla, oak",
    pallet: "Floral, peach, pear",
    appearance: "Gold",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-6vWL1whxyl5IPQ-gYZsIsODCQ9StENg3Jax4w803QcGFlLxxw9t_e-soODBmBAwk3urx5g3Uo5zcwSguQpGA9sGlQdPE7Nj6j_zqbgwvl1xTVDAollPRK6d-YwmowweXhyauTyKSM6EXEQ6q1U4cE=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Caballito Cerrero",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 46,
    aroma: "Cooked agave, freshly cut herbs, salinity",
    pallet: "Fruity agave, pepper, dill, pickle brine",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_imS6nbPsEafeP1oIx_aj1mtzyfoVXr7P_b409BDLnQzI4v-maWawT46na8qcNauNMXyvhUh9GjgGX3TyPDLRnSvgnL6g_ypbwvnYuH5q4f8EOtgYESScvwAFjbth_MKLfGjf8Idbbgrrrwp-howIE=w286-h530-s-no?authuser=0",
  },
  {
    brand: "Casa Dragones",
    name: "Blanco",
    origin: "Tequila, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Fresh and herbaceous with notes of green apple and grapefruit",
    pallet:
      "Balanced with semi-sweet notes of agave warmed by hints of pepper and cloves",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9wRYuFxtBsgRfVrzdfQEsZebVAXknNsCqf1NUnod7B-_kS3_iWwVFzwfJ3OyPoxnWR3xbvV4QNGsWv3tq6PDgRREhD6JrmGdPUFasQPh_JkLS7XqrbEpxeSNFSrjFnZ0mhU2nUUrvUM1_rS5pyidLA=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Casamigos",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Hints of citrus and sweet agave",
    pallet: "Fruit forward with notes of vanilla and grapefruit",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-WvWWoblovh5Pbd3r5UqCDE2gIloJtk_2qXZiYhhH3cQjULwE4as9TBXdAiykQkT3d0c29zU6vblicvQ_L1Rn6_q0R_RQpWLbvMC0Fv9ZyObHDuuTKfUCDBiS7iZPWod60teRc6HMUNkzQinTL_pqe=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Casamigos",
    name: "Reposado",
    origin: "Jalisco (Highlands Cienega)",
    style: "Reposado",
    abv: 40,
    aroma: "Caramel, hints of cocoa",
    pallet: "Dried fruits, spicy oak, sweet agave",
    appearance: "Golden honey",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc89TYDwLx3Kc9m4eYSdS9NDNHOz1eAKjV5mK3CHo56lxrBn4gpvYGJ_cpqut5nwb5OPiQ3zPpV4P1zjIMMZgjfk08Wwql5C5nezoOVQZQZQkoHviSMWxBE83JSB4ljSAZVPVkdHJp-DaQdH0qlZtYG1=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Cascahuin",
    name: "Plata 96 Proof",
    origin: "Jalisco (Valley)",
    style: "Silver",
    abv: 48,
    aroma:
      "Cooked agave, pepper, fresh herbs at first, then cardamom, walnut, coffee, honey and butter",
    pallet: "Mint, fresh herbs, honey, bitter and sweet fruit",
    appearance: "Clear",
    how_to_enjoy: "Cocktails",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8SYQ2vjPWZCYWqOYMve3xKH_XPJRpARFZzuTKQ6oh09z5PfvGUxOTZLGzwWhjDBPcuJPcKcERmhMr96sF3eyRwSzkJ2XyWz5qHv0nYE6itnKWRZcCxGMvrPg2MGrt5xXZNjfvHKuV_6Cgy0DltKE6p=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Cascahuin",
    name: "Reposado",
    origin: "Jalisco (Valley)",
    style: "Reposado",
    abv: 380,
    aroma: "Cooked agave, honey, vanilla",
    pallet: "Cooked agave, American oak with silky aftertaste",
    appearance: "Straw yellow, clean and bright",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_P3n6URNChDb27gHQp_phi_j_9rDpcKkdmOwnPJfAqW2daNdIHri1dXPG8YWyk1lV3BNtlP0yNFq9fcjGaKqfCuW3b3I-5phSrj9Uk55nSiNO7sn1ViESSkvKEq3mEuXmI84Ye4zpAiuMnSYoKuAEd=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Cazcanes",
    name: "Blanco",
    origin: "Jalisco",
    style: "Silver",
    abv: 50,
    aroma: "Floral, sweet agave, candy corn",
    pallet:
      "Clean and earthy, sweet agave, black pepper and anise. Finishes with long sweet floral and black peppercorn",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9g7OvAVsYkOu9CXeJxO5qDo-3NEduDpZH06iguBNAiHztMoF9f87uVlYDBR9megA4zuASNztr9jgubAlgyUyN2j7lAkCHQb3sRr7goQjxKjlaCfcO9rgiHxcuHNHPMq3BepzD47ziwmjKHwxkNvQmM=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Cazcanes",
    name: "Blanco Still Strength",
    origin: "Jalisco",
    style: "Blanco",
    abv: 54,
    aroma: "Cooked agave, lime, minerals",
    pallet: "Lime, black pepper, brine, anise",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc96oiTF_8AOym34fVDQ-m81qUAQqDCPKMGDKhx2Y4oW7f9NjaApAT8oD3Wta-movP3zW3wRrfGiQi1XFpX_UdRdBp2ONq6g_4-7U8zlS9ASoWOgqrVIrgZMOqsW6IkJShwvxVCSx2sm-QGhs_inveih=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Cazcanes",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma:
      "Heavy sweet agave, vanilla, coconut; slight hints of nutmeg and chocolate",
    pallet: "Warm spices, vanilla, sweet undertones of coconut",
    appearance: "Amber",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-zLw2zTaVggeDpsL5i92VNhuhIipHnwRqYBWbJURWrdxX4k4bbCA68oNrz74bz0I_SYsVCzxk6AaJDzNuHouiQimCwSl0C_-cgJMrtXwgGmI5enuPL0r7tKDknnT8P7OdDuWHRlQ1OTnZsHdw7zOiH=w355-h704-s-no?authuser=0",
  },
  {
    brand: "Clase Azul",
    name: "Plata",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Black pepper, mint, vegetal, citrus, green pepper",
    pallet: "Mint, minerals, herbal, peppery kick",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9BuVB9uiFoPrM3v1vOJa4IsCBlrksIRZzsSn3glR31O5tmbjm5jyfsNrPDj-3Xp42kG1zrGS01S3wflz75FPbQr_bCzwAtN8Zvnpr0hPBfk3e_Dp6JskzPxiH38Jp5xBpT8iKje24tuAJU1B9sccrc=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Clase Azul",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Vanilla, caramel, oak, butterscotch",
    pallet: "Vanilla, oak, butter, honey",
    appearance: "Gold with bright yellow highlights",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8lZRpckXtmXnhW8miqUlWrgbJCAhgEyaeX68E3flOG4BozJqtQ3j-NzcpV2KpzItnu48NaI2H790MZI4PR3HjijleEv31ZuQxc2pG-gSee37ch0roOZ5JdF7ukcrS0G9frSP2SIFbLlyMGuEik7qxc=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Curado",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Cinnamon, clove, earth, pineapple, grapefruit",
    pallet: "Smoke, earth, white pepper, baking spice",
    appearance: "Light golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_RpUIEn1Rh40aruDB5YLdQv2aj8Ei08aMsF7IKF8lp67ZNOk8RRZvR8to8Nc5vKG9J8cfwYbKB4nQjUo5mKNhDNVtQEM3IyPnmVJvIVskBgGNG9KIkkVkopu-2_LY3J45ot5g_4kEVhz-NSiB5_hoR=w447-h559-s-no?authuser=0",
  },
  {
    brand: "Codigo",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Black pepper, mint, vegetal, citrus, green pepper",
    pallet: "Mint, minerals, herbal, peppery kick",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_zoaTw8G165tGwAIlesNEGtE9mQkA5re8VV4k4oBalMgr8SBha1BaZcBeCqeRgm6jGS8iNoUU8ChzfGmSBWCMi9yeKottkQMZK83mAlKsaYA_HvDF4BANP39MM_53sLT0WkZFmhZVHDkdQl1ijkOEv=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Codigo",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Oak, vanilla, caramel, pepper",
    pallet: "Cooked Agave, vanilla, oak",
    appearance: "Maple",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-xi1NvC8LD4I2CiCCu2_Iysvlt4hNgyLb-Py57yud0Fc9CTrV8gznOELY-Dr1ky1A4MK37AcUt7JPRFvGyY_-BG_MhO9NxKcD90bsUCb2tvGWUDsNRXZQW7DT71hMPK7s83M0ML4wh71DRWKXdiqms=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Codigo",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma: "Butterscotch, caramel, oak, citrus",
    pallet: "Spices, oak, butterscotch",
    appearance: "Golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8_ua95IB07CASwAKqk1uDCbtrlu2wjSjn3tdE7o5WjQFzJkUmWfQFWIHLZ2dHl9OJnvl68TT7UYY26u52NetGrfpgHfbSDMWdE5r3gYm2eX38wv7ntt_TK7Fralk9wpjo-YNX_r6iKp_Z49Zg2o6ku=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Codigo",
    name: "Rosa",
    origin: "Amatitan, Jalisco",
    style: "Blanco",
    abv: 40,
    aroma:
      "White flower bouquet, cooked agave, tropical fruits, pink peppercorn",
    pallet:
      "Cherry blossom, honey, wet earth, cooked agave, rose, mandarin orange, toasted oak",
    appearance: "Pink hue",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9fjVm5CwvcFf_SkyCgTEEHq9cTy7EmFkBpW8u4aBb-QErArZN_GHcJxjnpDSQ2Zf4AYImvkOVopuxlU1MX_YXnVxGrzwF4qBf3Io3Je33kcQg2eYzU0gROhhdK9A5OZLVTkTnT4WcMvZ8TAKW0J9by=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Don Julio",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Lemon, lime, and grapefruit",
    pallet: "Sweet agave, citrus, touch of black pepper",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-0I5icfq-ec_FFdhsfaQu_0_bLZmxPqGfUbFwHUkgDzk8h8xizxmNfQGjadg38mZ9UpdDQHs3NeT4xmshgUkmMmhmHsB2iuQyA2_AMjlS1nSdwuN4mZBpY9Dgzm_B4U5pDYp882FjHJNW2dDfyr1wA=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Don Julio",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Cooked agave, vanilla, caramel, oak",
    pallet: "Cooked agave, pepper, vanilla, caramel",
    appearance: "Golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-8D5ywv27h7oTl7HVp-OROOcUqvGxrcVSB6xY7IqvlAoJbEe6R6oCS70rQqZN2PDIeDHqWWqm5u4a3x54Nm4blmD2ykfXL1F46DY4IKzy6b9R1XLdvYR6H1x7fAeOqqFOLoagDrYGML3V1YRMeiV7h=w900-h660-s-no?authuser=0",
  },
  {
    brand: "Don Julio",
    name: "Anejo",
    origin: "Jalisco",
    style: "Anejo",
    abv: 40,
    aroma: "Vanilla, caramel, oak",
    pallet: "Vanilla, butterscotch, butter",
    appearance: "Light amber",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_oneQ_1CDfK3OOFnuCIC9H2ZE2mNxd_i8Z1bIiGDstBMd0qMLP6WlJVKX0p9Mr0oVLvAAFGGc8Izg8xZAcyFK85DIb6eGIh_g_BPQo9NneC0DsNAVp5t2IggX7Jderue17Tyhcg93TAU2UJcXN8ktZ=w488-h488-s-no?authuser=0",
  },
  {
    brand: "Don Julio",
    name: "1942",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma: "Sweet, fruit, brown sugar, wet oak",
    pallet: "Vanilla, agave, clove",
    appearance: "Golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc86uy7k7BNS6mgWV08P8_8onMp2uBfkAJUmaPDBXv81RTPCFC0YXNqV6jDYC90v7vpQiHXRpkFAbPsDbjwLh7joHwGRo_LkzqGB-45iCUpVIME6wq5TE5GBQFcC2-asd2pG7ThKxGsrjpEGDz243TP7=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Don Fulano",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Crisp agave, citrus and herbal notes",
    pallet: "Sweet agave, hints of pepper and floral undertones",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8H-TRB-497_MtMvV2Eeu9EdELJa-Ide9LTV4Ojv_rjGnXzAJ8yGfC44-fDj9PKxrmHSBhjN3k9ymBpnWHqGaoa0hkD1uUK7WSzGhr43Ah6wfdvwDaQfQGlJmXW0rHqCtu1bCmRE14rwcofyOPlJ75g=w367-h679-s-no?authuser=0",
  },
  {
    brand: "El Tesoro",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Earthy agave, floral and herbal scents",
    pallet: "Sweet agave, citrus and peppery notes",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9I0mEkVNyIyW0FYcPI0r8ds_sODP9hL0rtTsKqEE_R-FDnCcHX1zJoFtQxKb2SdRuVTBlWA7O6Ayewv76ImoSEOIQKTERrJQNRfV50_CHIIYIgNwI7pxBi3moqi942EO0stn5cy2mdAZ7LA5wIBOs0=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Espolon",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Cooked agave, fruity and slight floral hints",
    pallet: "Agave sweetness, tropical fruit and gentle spice",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_HuTDb0PO9pzV3ibxKkz-ti4LGuY677cCmUtt1Iztn58Nhsbn7h5AM371KWPCu4MDmA6Fj8CNXyEQqda0IAPeyyXDqrzneQYoPdOQQ4WkpyAGc_d9ybX_s6U_nLL7exiQTNMzfUJAlfXXfzstmsxXV=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Espolon",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Agave, vanilla and caramel notes with a touch of oak",
    pallet: "Smooth agave, butterscotch, and toasted oak flavors",
    appearance: "Pale gold",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_Nqejvwfnb3z9aEJ2OiC_DlluKlxIQy73Nw2UDOHunXbTQIzF5MvZ99afzei5HX45Yl_HoLtkCpy6p1uxFWVrC5fwu1rxTs6fqc7lDmEcFsqChVWx93Y4xUGLX8ZGsg8aenwVhQCZE-6gDi1f4l-43=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Fortaleza",
    name: "Reposado Single Barrel",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 47,
    aroma: "Cooked agave, prominent oak, astringency, caramelized apricots",
    pallet: "Deep roasted agave, vanilla, fresh herbs, black pepper, cedar",
    appearance: "Slightly darker golden than traditional reposado",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-1xrOrlq-Q5qu2mjiOTXGvTGs6EYBUyPvV0apg1iSoVGV6qmChtg-e8kBUp_fSevLESRIpAkVwvdpzOK-1cOkE-gtsa5zPKMhY_OjggvjdtF6319V9JSl8aMWatHtiV2piGDCtccyaKxcZWJexjKca=w442-h565-s-no?authuser=0",
  },
  {
    brand: "Fortaleza",
    name: "Winter Blend",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 43,
    aroma: "Aroma of vanilla, caramel, oak, citrus, cinnamon",
    pallet:
      "Smooth and full-bodied, dark chocolate, honey, roasted nuts, long and warming finish",
    appearance: "Golden yellow",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-VL8N3W12fKnmKNkpnC2cTrdMYQ2VQlHogrJMDHqtmzWRo9GYfplJdXi3pQQDB7P8y2Lkkkus1N442otnlxEOQe0qaaSbH1X-LxzEgvvHgzMELPD4_9urTT1C4gICdc478G-vFKpMOCtyucrUutryC=w367-h679-s-no?authuser=0",
  },

  {
    brand: "G4",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Cooked agave, herbal, vegetal notes",
    pallet: "Black pepper, butter, smoke",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8RUKvYsG9daQJ_E-Hy1PQi3t9H3yH88ZxnyqVvsKrEg2WU2Ej3xJkZ7KpNigdrguvIeApq9qP494z4ONIdd34QITeyoT3FhDmI0nzc2wVsQTgZY9m1wN3Mc_G1l03tcwyw9_0KwIXI7EGPtP8fZGI9=w367-h679-s-no?authuser=0",
  },
  {
    brand: "G4",
    name: "Reposado",
    origin: "Jesus Maria, Jalisco",
    style: "Reposado",
    abv: 40,
    aroma: "Vanilla, black pepper, cinnamon, grass",
    pallet: "Oak, caramel, citrus, butter",
    appearance: "Light Golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-t2MCbThUJkl3GUe5vvbDU5j4GKSqLBo6OMD5lbJFLav4x1OZBdz8itBcU_gC2ZIJzFCqBlC-LXhp3H6e0aSVKsw0yLpM4GwHQZwQRCerkXP5Y5dYtVzvwwPz7y5AeoIFMkCv2GjyBw66AFYQ2xyWc=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Grand Mayan",
    name: "Extra Anejo",
    origin: "Amtaitan, Jalisco, MX",
    style: "Extra Anejo",
    abv: 40,
    aroma: "Sweet toasted oak, caramel, vanilla, cooked agave",
    pallet:
      "Sweet toasted oak, caramel, vanilla, dark chocolate, mascarpone, butterscotch, cream",
    appearance: "Dark Mahogany",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_m0pgnRVpOsAYBhEky_uL3ovuq4WQADG8HodN9mrlcjnZ9xmixktb8AE8C6KAIMh5gJr1cvAcKPcnf9Sp39OgFXoC3x_xDc8_bl7PKx17KNQD1CbEcZed-ZH_InNPJRshcKHKkZI4kCAEJOZy1xxuf=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Herradura",
    name: "Silver",
    origin: "Jalisco",
    style: "Silver",
    abv: 40,
    aroma:
      "Olive brine, tapenade, musty cucumber, bell pepper, vanilla, cotton candy",
    pallet:
      "Cerignola olives, dried oregano, vanilla, candied citrus peels, pickled jalapeños, asparagus",
    appearance: "light straw",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_gTPT15rpJYO8JKk6Nvs7soJpQmFAlv2L7hUfYVeXE4UcW0Ho0ztkRAbet08w6_sk185BDtsQleFFZYOg1zSfDPFbLm2P-fabWlgIqZV7-ctGRTImdvRRoCqeSVxUcnZ5ipGAYSl1ObqowpzcQ7m_6=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Herradura",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Agave, vanilla, caramel, orange",
    pallet: "Agave, vanilla, oak, spice",
    appearance: "Caramel",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_dq-nFYwQ-78knnsjngg0vy03uJbvfR1lW2tI52XVb6PSuUv7RhZkqrLjyEEEMMxMK85dUm14ip3gAKjAzJYOC2uTO054kg-YQaSEcWy2yT8MZ6UBjWSxxZ84h_Er-a1QGBDsJzsCjL7sBGNsnIY7i=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Herradura",
    name: "Anejo",
    origin: "Jalisco, Mexico (Los Valles)",
    style: "Anejo",
    abv: 40,
    aroma: "Oak, caramel, vanilla, honey, butterscotch",
    pallet: "Cinnamon, candied walnuts, buttery, slightly peppery",
    appearance: "Amber",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_cYhQ147FYqa3LjgqQ_I_JImLdKo5jAtsuccCBKJdpQlsIKe6mKIysXqQAwl-6fsgCcG-UyAjMoHFatgcfzulBnsfJHoRTtSmNpcqwVuPX3DIKR3le3VDzuthCMh1hmzm45BmgyFHE6Sp_8Wj3TWuJ=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Herradura",
    name: "Ultra Anejo",
    origin: "Jalisco, MX",
    style: "Cristillino (blend of anejos then filtered)",
    abv: 40,
    aroma: "Vanilla, agave, caramel",
    pallet: "Heavy coconut and vanilla flavor with subtle caramel",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_PgZ21IYY87Yb3o1T8Anle9OZe8u-WNi2ottD86Tg7oen48dLv1P2NzlSupFAeTSrSeGOi-GGDZFnQINuHR6WDbzPu-22gwIQS-WlBU17xuzESCTqucc2qOdmQmpYB0Sw5Rza7hHCgLfSoEwhlpxd8=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Jose Cuervo",
    name: "Reserva Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma:
      "Light aroma with grass and jackfruit, lime, salt, and sweet peppers",
    pallet:
      "Mild flavor with accents of key lime pie, vanilla citrus cream, baked prickly pear cactus, and bubblegum",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8H_c_HDOcUM6xhDkhipt4M5OVqeDiichSmZvp3O8CkMW3xyx3jWDZPUnDHmJcznkh_7Hb9MS5xjX9c3agJm6ktGFQKeWTAfkhKDxPAG9f3dTmhEuHewbdZUCFfB37H21G6OMqeHmehjpXHDjM8q7x1=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Jose Cuervo",
    name: "Reserva de la Familia",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma: "Zesty, dill, fennel, pepper",
    pallet: "Semisweet, caramel, vanilla, marzipan",
    appearance: "Dark Amber",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_l4UinhKuFOk44obVLL5vvpEntJ8MhqIWuDAZ6e52kMOMgO1AULBEt78P8ONz6X_cQT2IEKC3r-n1WyCFy4CCs4ynLIgl6OJaUvWglQxYnD5wM2SEoHkrwV_1CcJs555D3yJ9LB3I5sbZY5nuLCCdN=w500-h500-s-no?authuser=0",
  },
  {
    brand: "La Gritona",
    name: "Reposado",
    origin: "Jalisco, Mexico (Los Altos)",
    style: "Repasado",
    abv: 40,
    aroma: "Vegetal, light minerals, grass, citrus",
    pallet: "Raw agave, touch of vanilla and oak, slight white pepper",
    appearance: "Very Pale",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8F1-FD6JGflXW6NG48adTTIxY0E3yUQBPT1SlPXdVFBplfjTqfgi7B1fjrbHY3ThrTiqDGowVW__qyWWgBXA_nBMKiUZKM7d2ibPxU13FQ-p253z5ZYCzp_uMaN4fT8hqd56QOkCgde-sn-V4fI_w0=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Maestro Dobel",
    name: "Atelier",
    origin: "Jalisco, MX",
    style: "Extra Anejo",
    abv: 40,
    aroma: "sweet, buttery, vanilla",
    pallet: "Lovely, mild on the tongue",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-G_N3yEyn76h_TfuRzYvVM2EAq2vbqzGyoHFJulizqyKVNWZR2X2OJzXdPDP6mndbdYjHHbv2T02WaFqJBJHsbhXrMt6nagBa66wHxN7bUWLQglMuiMrIjO1dtTU2o_GdySPTwOG0jAtnBav9lyHz0=w299-h600-s-no?authuser=0",
  },
  {
    brand: "Maestro Dobel",
    name: "Diamante",
    origin: "Jalisco, MX",
    style: "Blend",
    abv: 40,
    aroma: "Vanilla, pepper, citrus, oak",
    pallet: "Caramel, honey, maple, vanilla",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_Qz1yOZNI1wvmblHS7Db8_Bm8_r-gGDfn_9GuEDHKZh6NaakVZUONa8oEMvPCWYgg6rhpH_MVtubdM_T5MfqfCNKqJzv0v2IS2ZbqzdBHLSM8YhEMneaj4GlIl2PL9gB0X8PLBcO96VHCUHRf5-K9W=w480-h520-s-no?authuser=0",
  },
  {
    brand: "Maestro Dobel",
    name: "Humito",
    origin: "Jalisco, MX",
    style: "Silver (smoked)",
    abv: 40,
    aroma: "Smoke, agave, black pepper, earth, vegetal",
    pallet: "Smoke, tobacco, charcoal, wet earth",
    appearance: "Clear With Touches of Silver",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_Hfbjsung27u2Fkzkgo8O8ZVcW_-B1i3WVk1dy3NDL-ve-U6XQLL1vd80T0Z7znR3nOewx-p27KShxCpweZ5I27Hzizvm7jSWAeQQZlq-aHGbzN0kOBA8owZKAhUsvsbit52fJM-lO-ajJXWNxyIr7=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Maestro Dobel",
    name: "Silver",
    origin: "Jalisco, Mexico (Los Valles)",
    style: "Joven",
    abv: 40,
    aroma: "Buttery caramel, olives, and dried fruit scent",
    pallet:
      "Range from caramel, honey, and maple to nutty with notes of vanilla",
    appearance: "Bright and Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc90Qeo34oGuH7UACDutLtKaMTFCMF6LdOgFM7DgIlnHTiWvuP0buFvac1Fi0cMbVrS4sag-gkY0Ll4x8rV9S7-vRxevK3wFcMWpt6ptGypwR_dDcr0_NgQ7Q6rhheM3un-k9Yf7kYPLFRDA1a3L-ldh=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Maestro Dobel",
    name: "Reposado",
    origin: "Jalisco",
    style: "Reposado",
    abv: 40,
    aroma:
      "Buttery caramel and fruity notes, with touches of cinnamon and almond, with a slight hint of smokiness from toasted wood.",
    pallet:
      "A mix of sweet, nutty, and vanilla flavors with indescribable smoothness and a long finish",
    appearance: "Bright Gold",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_FVx2vVGQMWjtbJBc9Cnb-X1Rciw3G7RaP5mbJixzwHdvPuOp9ne-Hj_ChWFXiUUppm-deTE3mscCR7FnVnb167V7YuCQq8ZFgTqHVcnXVMIvUY-jD_MBNU0eEqbSZaN1Zwf_pV2bjm0ZZjAMAzYq0=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Maestro Dobel",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma:
      "Buttery caramel, almond and cinnamon notes, pineapple and apple with a slight smokiness",
    pallet:
      "Wood interspersed with sweet, nutty and vanilla flavors, with slight notes of agave and fruitiness. It has an indescribably smooth, long finish",
    appearance: "Dark Amber",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8fTNzOuAnJe2AofhbprDpVmKJ9qB80RlOe4FvdXlHe7_ITB8c8QWpMu0Zvh7Tb-a5aiIHtdM9WQm8UPs_2SWOyqwcWpINPpTPDPZxwSy384TLqyJjrheqpbgV6hh83D6DklykExyZsnn6I_X-q25yN=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Milagro",
    name: "Select Barrel Reposado",
    origin: "Jalisco",
    style: "Reposado",
    abv: 40,
    aroma: "Golden honey, buttery smooth",
    pallet:
      "The taste is clean, vanilla, with white pepper and cinnamon spices and a dry finish",
    appearance: "Clear with a platinum hue",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-Gc4gUJSaWhPn795k6oQsNOQJxCTUM0iFdqMazLXcTBYX8p51N8oPLJ85agbqr_BiDgFnF0bQzwitZEMJo0gFX_uwa8zh5wnMIJP4vwKAbkcq8SSer1ibjOZ18AetGx2u56Rhyr03ClUPSXX0wqCyh=w293-h852-s-no?authuser=0",
  },
  {
    brand: "Milagro",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma: "Oak, orange, toasted coconut",
    pallet: "Agave, stone fruit, butterscotch",
    appearance: "Light amber with golden hues",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9uFte8K8o_oej7639fTXmKXu1lfcX7ZIe0772YMor9rtIvQkEhccsHavkMT5RhgluIAnFTB4x3_LlNK-mlBBmf0Tz-OGN9zIo45KBNKhz3imazy61EiFrfGfLVmIIaxEsAEPXRURWzuN4xPBvEiY3E=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Mijenta",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Cooked agave, citrus, pepper, flowers",
    pallet: "Cooked agave, pepper, citrus, butter",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_mljUPDQyx2UyBzcQBDEoTiGgwFBFmTNSjGOZVPLwZVPWvUDDu-ggJVOytwLz5hO4kyxnvSHCfNLBPH_U5ekIHI0-6EjzWYG1LDaO_Zm13vUO7yHRgoTBXSfLt2XXnAw56jn6tAl9hfM8lKx86QW48=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Mijenta",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Cooked agave, oak, vanilla, banana",
    pallet: "Cooked agave, pepper, oak, banana",
    appearance: "Slight amber color",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9ZduXtjWPzAntJjR2lLk43Yens3dS4Ya0AfSTUhVELWU9zUI3CwtZbq8Taao5kc8oXZXVG6jn3B7mLgGVh65MVTPj0xxwFK9UjimLbX73mgbWuClFkFOny0cCNIi1Ao03yhA4tNbO6dGfTswRDv8tl=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Patron",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Silver",
    abv: 40,
    aroma: "Fruits & citrus",
    pallet: "Smooth & sweet with a light pepper finish",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8Pe9-qRzO1NTbd7OBQJwZwhl2p2xySPHZdswfyZLWalwKg6PE7y3PmLb0VBGkVvmLbnYnSfBD1KQ9jIB6BRAavtyqidojlufXIW-51wus30uPWOvKyzeUTGuZ5NDvBkzyHyY_H8XHz5eRM_dPPfYUD=w400-h603-s-no?authuser=0",
  },
  {
    brand: "Patron",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Oak & fresh agave",
    pallet: "Fresh agave, oak, citrus, fruit, honey",
    appearance: "Light amber tint",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8cMrl1UIMk_rjThA06SdHQSafr-OOPrgfK4M-37DFl2fusA7kKsyaz_WEqHHYMqi9SIG3dul8t8d2FCIMQ0TsRKR4c037P8izyq3xPZSgrV-S1dAeJjuSsKe2GfiwcD8TtyxA-ebQu6MEbxhxq3Y3w=w400-h603-s-no?authuser=0",
  },
  {
    brand: "Patron",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma: "Oak wood, vanilla, and raisins.",
    pallet:
      "Oak wood with notes of vanilla, raisin, and honey with a caramel and smoky finish.",
    appearance: "Warm amber",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-5wIK9bJVbri-YjSCFoFL0IQ462Inx3VEmhHdSSp8NvOYR3NatLPntb4_6FwsfIT9Gtr9NAvQ28DueBolpjvKwX-v1KR_zE-sidBFLFjJw5NZHsrcfiOFFKlwXvaLgAYMuZ6RsIQMet-LFIheN8sfQ=w400-h603-s-no?authuser=0",
  },
  {
    brand: "Patron",
    name: "Roca Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 42,
    aroma: "Cooked agave, oak. vanilla, caramel",
    pallet: "Black pepper, whiskey, cinnamon, wood",
    appearance: "Light golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_KRltmFjafd5oJ43haQKuSg1pCVcvifKQlN3Cy5qPqbFj_EK9xIyAuz4Kqka8qMslj2S5J4taC81NyYJkSFldEkcVuYoB4YGBcA-RBy4tzBKzHXTI7DSVamAURncHKeqHxhilbqHobEqN1F2D9ZClQ=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Siembre Azul",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Citrus, cooked agave, pepper",
    pallet: "Fruity notes, cracked pepper",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc82WVAtrmzo8A4mH7YHk3plhvMnHKU4DS6QhIA117X2s7OcxiiuAQqrKMXLAiW8Hvc8EheANyeUDyxuKrj4ueB-oyntESG9hnyx84nKvV9pBrOs69okA4Kk0sBdA39dkvPbGMnBXwMiu3Hu9nxtrt6g=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Siembre Valles",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Citrus, caramel, vanilla",
    pallet: "Vanilla, oak, mellow agave",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8LnT3U6m0OFaHX7UdxoMdXvmVnazvOQI-otRYl-h46Us2PeEdeNua-kxcw11Z8ijzwiiN0sNrB85RLZlUy20b-C_55b5FcOiBuBi7pFcMxI1nXDkAhFVwfYO58K_-z3rUtWBjN0Q7I8PjE3x0zZZZ2=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Siete Leguas",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Black pepper, earth, vegetal",
    pallet: "Crisp, bright, citrus, peppery",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc949aDRcFYtsfPZwzzqEtofxL2l3jS_PJrmLW87CLIZ0wkSEBpaEOsjKiQi-OGrybv-f5uIKWn0LhghGNaGvl6WVqiSWkq308M95cRNWy9l_hwRbGK2WXvV2XsUW_xmHrO7wRY0Buls4AMTZeHIWCZw=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Siete Leguas",
    name: "Reposado",
    origin: "Jalisco",
    style: "Reposado",
    abv: 40,
    aroma: "Agave, oak, citrus",
    pallet: "Slight sweetness, vanilla, caramel",
    appearance: "Golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8o4hYjDGlfduIjfL9gZNzD4tgTjKX25LRKfdxEXBXzWh8Em6OWErpJw3uezZizhCb7v_cWJn2EZ3trOzdRDuI3d2dTpjqC5jnoS2vhlTnh911Pq6qymGmPc7MKMbm7qrYlqmwtiFV2O6NA_RmBSB58=w500-h500-s-no?authuser=0",
  },
  {
    brand: "Siete Leguas",
    name: "Anejo",
    origin: "Jalisco",
    style: "Anejo",
    abv: 403,
    aroma: "Agave, oak, vanilla",
    pallet: "Caramel, vanilla, toasted oak",
    appearance: "Golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8ebwBNIt-2ZXmdUe_aRaG-CxaiVE2OWnO_5gprjk8YHkMq6CQq7bhY5zAObMQ_9MkGDZTQQkvUq4tkQblxDPm1T9qqSm3UKRUX3aINJERc6QuJ2uNkySqNcxBktQPlyIpfIqq4Uho2tVqAOwLjqib8=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Suerte",
    name: "Silver",
    origin: "Los Altos, Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Cooked agave, citrus, vegetal, black pepper",
    pallet: "Sweet and vegetal notes, cooked agave",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8tXGFa7dMcuyhAITM92ErakgTDB0RT6Srpda0Tc9SlMX51ohr5cAtWOBzAORwZIxQdirrlfQzilnRlTfTRTUDKhCHQljgnoqT0WGEgx9Psn8HGFvbPJccfmRaIMUf7kYDWxx-EYlEjK5aIuvEThLyp=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Suerte",
    name: "Reposado",
    origin: "Los Altos, Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Vanilla, cooked agave, caramel, citrus",
    pallet: "Oak, black pepper, earth, cinnamon",
    appearance: "Pale golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_bZuP0_3PnQsFVMDA9qagTIrbKAkU6ls3yJPgMtaTCdpvBHXOcPsIucBW_0eehn4aX7cT95zL3F-8dNJAvkL3STvbd9_VjKzWi1mlg22gqd_NwXZk-3xafvedpki6EwEwKYJG1wEcoYTs2q78PcK7D=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Suerte",
    name: "Anejo",
    origin: "Los Altos, Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma: "Oak, vanilla, caramel, fruity, butterscotch, earthy",
    pallet: "Oak, cooked agave, butter, caramel, apple, baking spice.",
    appearance: "Amber/caramel",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc9eAaukBCeiBw3EtVBjKM3BJkj9hfEwTyO-fdQK5GOTtUBzdTRHmQBL2uBemH9SXNHkT74PwxijddwXv7SJdV6D5e1DpyqoZYsE7UptQ6aEYhH1ZD6tuiTHaI5l0xpXaJ9izvV86Nqd2oye0IT_s3jt=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Tapatio",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: 40,
    aroma: "Herbal, earthy, vegetal",
    pallet: "Agave, peppery, grassy, citrus, blast of cinnamon",
    appearance: "Clear, silver tones",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-xJsrZg8QBC9EQpoVj9heEUgQ1vpZhXmGqvdA0B4_jDCRTJT0mmQNb4lJRZ1hnwIKNrbmTS3VmpKphiKyB-wxa--kdn9rmT2UzK0lKlDnRi3vafWdbEV-QH2AoUXCmXozjY-mZr5ZDLuaCVtnoYVuS=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Tequila Ocho",
    name: "Plata",
    origin: "Jalisco, Mexico (Highlands of Arandas)",
    style: "Blanco",
    abv: 40,
    aroma: "Crisp, bright agave, herbal",
    pallet: "Full agave, fresh cut grass, earthiness",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8e3LTv9vABENM901MHOpvtg1piK5uCYORfIENpT0-zM1C9DwWHtLozkNK5zH-sMfaHianCG23d5xoR5IRrxpyo_tzvXxSIj0ifvc3dkSWZ8VIVddNLhdAybCYhMSaYv5PGT6QSMXwWuQB3Rui3WtyJ=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Tequila Ocho",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: 40,
    aroma: "Cooked agave, vanilla, butterscotch/caramel, oaky",
    pallet: "Nuts, orange, spices, sweet, clove",
    appearance: "Translucent amber",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc8XI__MGL_jHMqxNkVqUupnJyvKHuiArv0SgbCEyY1YjQYpAniKvjBSuAD6_upPeW-LbHYz5dY3pATJ79vI5WEkmiKy-GZBKh3n7VjGHAIHnJvsVW6p7yF_5EGt1-tl_erMnX4a5ufb4V0cEWsQOzzx=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Tequila Ocho",
    name: "Anejo",
    origin: "Jalisco, Mexico",
    style: "Anejo",
    abv: 40,
    aroma: "Floral, mild, light chocolate, agave",
    pallet: "Honey, butter, cooked agave, vanilla",
    appearance: "Yellow/golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_xPWqopn6U5X78TLUYt8JThMIsNnWbmwSblIaY2U9NZez4F9yOPi9yCB-J5JqNwPaQ41oVl8tB9z3QSOAjTGaq4l5d0feaMF7Ye1jN_6X0jRkyU1yses33h6igjQgG3-6T3VImUbdHoHOPgivvrF1S=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Tequila Ocho",
    name: "Extra Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: 40,
    aroma: "Agave, vanilla, oak, caramel",
    pallet: "Agave, oak, vanilla, citrus",
    appearance: "Light golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-AHhUFMYJIyZJXD-Yqck4IpKw-7ZVnR2KPcA5Bp1C7ZYwHgDPrakFBPSJ91DFBoYMXS1IA17OtaKfB5-3nq_hmJKkjFdrnOJ4lXBsl498F8V4ADSP5t90jZtBA91EDY1yV-q65SQmmsIa9UFA0ZU_8=w367-h679-s-no?authuser=0",
  },
  {
    brand: "Tromba",
    name: "Blanco",
    origin: "Jalisco, Mexico",
    style: "Blanco",
    abv: 40,
    aroma: "Sweet, citrus, agave",
    pallet: "Herbal, citrus, caramelized agave, lime, honey",
    appearance: "Clear",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc-2x9dn849ekxjvBdyhMF3qC84__EuoZQzJD1SnjECC28ThUV2wqs5ozFj803AgjG1jKCn2mAJmLgpvwKBZtt5_zNWWvEZJge3Z4joVW3X-yCDAylBTagfAGLxQ7AaaKaVoRLoEXGxzayX1vD6fmEW4=w422-h591-s-no?authuser=0",
  },
  {
    brand: "Tromba",
    name: "Reposado",
    origin: "Jalisco, Mexico",
    style: "Reposado",
    abv: 40,
    aroma: "Roasted walnut, smoked wood, cocoa",
    pallet: "Chocolate, brown sugar, nuts",
    appearance: "Yellow/golden",
    image:
      "https://lh3.googleusercontent.com/pw/AIL4fc_SGKc1g-jyD8nqBxKlrpuGXS-UCqBKzon1eSe9X1Um35eZbLYC4Eq1RuBaH6gygbob6vPdCfQB-nund_uUIMPSgrVZKoqfEjEmMCEmvy5Pw1pPAzjHbB--GOo_j15Y2akdgw6gMEoM3qv-z1NC9nMy=w500-h500-s-no?authuser=0",
  },
];

const seedTequilas = () => Tequila.bulkCreate(tequilaData);

module.exports = seedTequilas;
