const { Tequila } = require("../models");

const tequilaData = [
  {
    brand: "Tequila Arette",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "38%",
    aroma: "Baked agave, lemongrass, fresh herbs",
    palate: "Lemon, wine, herbaceous, vanilla",
    appearance: "Clear",
    how_to_enjoy: "Perfect for Palomas, ranch water or margaritas",
  },
  {
    brand: "Tequila Arette",
    name: "Artesenal",
    origin: "Tequila, Jalisco",
    style: "Blanco",
    abv: "40%",
    aroma: "Herbal, citrus, vegetal, spice",
    palate: "Spice, pepper, minerals, vegetables",
    appearance: "Clear",
    how_to_enjoy:
      "Best with lighter meals like vegetable, seafood or citrus-based dishes.",
  },
  {
    brand: "Altos",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Vanilla, wood",
    palate: "Citrus, oak, cinnamon, black pepper",
    appearance: "Gold",
    how_to_enjoy:
      "Pairs really well with cocktails. Could be used as a sipper.",
  },
  {
    brand: "Atanasio",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "38%",
    aroma: "Cooked and green agave, mint, basil, green apple",
    palate:
      "Cooked agave, vanilla, tropical fruit, cracked pepper, vegetal notes",
    appearance: "Clear",
    how_to_enjoy:
      "As a traditional tequila, any classic tequila cocktail would do, such as a margarita, paloma, or ranch water to bring the pepper notes out.",
  },
  {
    brand: "Avion",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Roasted agave, vanilla, oak",
    palate: "Floral, peach, pear",
    appearance: "",
    how_to_enjoy: "On its own or in margaritas",
  },
  {
    brand: "Caballito Cerrero",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "46%",
    aroma: "Cooked agave, freshly cut herbs, salinity",
    palate: "Fruity agave, pepper, dill, pickle brine",
    appearance: "Clear",
    how_to_enjoy: "Sipping, rocks, Ranch Water",
  },
  {
    brand: "Casa Dragones",
    name: "Blanco",
    origin: "Tequila, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Fresh and herbaceous with notes of green apple and grapefruit",
    palate:
      "Balanced with semi-sweet notes of agave warmed by hints of pepper and cloves",
    appearance: "Clear",
    how_to_enjoy: "Sipping, rocks",
  },
  {
    brand: "Casamigos",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Hints of citrus and sweet agave",
    palate: "Fruit forward with notes of vanilla and grapefruit",
    appearance: "Clear",
    how_to_enjoy: "Margarita, paloma",
  },
  {
    brand: "Casamigos",
    name: "Reposado",
    origin: "Jalisco (Highlands Cienega)",
    style: "Reposado",
    abv: "40%",
    aroma: "Caramel, hints of cocoa",
    palate: "Dried fruits, spicy oak, sweet agave",
    appearance: "Golden honey",
    how_to_enjoy: "Great in margaritas or on the rocks",
  },
  {
    brand: "Cascahuin",
    name: "Plata 96 Proof",
    origin: "Jalisco (Valley)",
    style: "Silver",
    abv: "48%",
    aroma:
      "Cooked agave, pepper, fresh herbs at first, then cardamom, walnut, coffee, honey and butter",
    palate: "Mint, fresh herbs, honey, bitter and sweet fruit",
    appearance: "Clear",
    how_to_enjoy: "Cocktails",
  },
  {
    brand: "Cascahuin",
    name: "Reposado",
    origin: "Jalisco (Valley)",
    style: "Reposado",
    abv: "38-40%",
    aroma: "Cooked agave, honey, vanilla",
    palate: "Cooked agave, American oak with silky aftertaste",
    appearance: "Straw yellow, clean and bright",
    how_to_enjoy: "Cocktails, neat, and rocks",
  },
  {
    brand: "Cazcanes",
    name: "Blanco",
    origin: "Jalisco",
    style: "Silver",
    abv: "50%",
    aroma: "Floral, sweet agave, candy corn",
    palate:
      "Clean and earthy, sweet agave, black pepper and anise. Finishes with long sweet floral and black peppercorn",
    appearance: "Clear",
    how_to_enjoy: "On the rocks, neat, cocktails",
  },
  {
    brand: "Cazcanes",
    name: "Blanco Still Strength",
    origin: "Jalisco",
    style: "Blanco",
    abv: "54%",
    aroma: "Cooked agave, lime, minerals",
    palate: "Lime, black pepper, brine, anise",
    appearance: "Clear",
    how_to_enjoy: "Best sipped",
  },
  {
    brand: "Cazcanes",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: "40%",
    aroma:
      "Heavy sweet agave, vanilla, coconut; slight hints of nutmeg and chocolate",
    palate: "Warm spices, vanilla, sweet undertones of coconut",
    appearance: "Amber",
    how_to_enjoy: "Sipped neat",
  },
  {
    brand: "Clase Azul",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Black pepper, mint, vegetal, citrus, green pepper",
    palate: "Mint, minerals, herbal, peppery kick",
    appearance: "Clear",
    how_to_enjoy: "Mixed drinks, paired with fresh orange",
  },
  {
    brand: "Clase Azul",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Vanilla, caramel, oak, butterscotch",
    palate: "Vanilla, oak, butter, honey",
    appearance: "Gold with bright yellow highlights",
    how_to_enjoy: "Sipped",
  },
  {
    brand: "Codigo 1530",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Black pepper, mint, vegetal, citrus, green pepper",
    palate: "Mint, minerals, herbal, peppery kick",
    appearance: "Clear",
    how_to_enjoy: "Mixed drinks, paired with fresh orange",
  },
  {
    brand: "Codigo 1530",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Oak, vanilla, caramel, pepper",
    palate: "Cooked Agave, vanilla, oak",
    appearance: "Maple",
    how_to_enjoy: "Sipped neat or on the rocks",
  },
  {
    brand: "Codigo 1530",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: "40%",
    aroma: "Butterscotch, caramel, oak, citrus",
    palate: "Spices, oak, butterscotch",
    appearance: "Golden",
    how_to_enjoy: "Neat",
  },
  {
    brand: "Codigo",
    name: "Rosa",
    origin: "Amatitan, Jalisco",
    style: "Blanco",
    abv: "40%",
    aroma:
      "White flower bouquet, cooked agave, tropical fruits, pink peppercorn",
    palate:
      "Cherry blossom, honey, wet earth, cooked agave, rose, mandarin orange, toasted oak",
    appearance: "Pink hue",
    how_to_enjoy:
      "As a lightly rested Tequila, it is ideal for cocktails such as a Rosa 75. Usually best paired with a red meat entrée, but can also go well with vegetarian meals such as portobello mushrooms and certain cheeses.",
  },
  {
    brand: "Don Julio",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Lemon, lime, and grapefruit",
    palate: "Sweet agave, citrus, touch of black pepper",
    appearance: "Clear",
    how_to_enjoy: "Great for cocktails",
  },
  {
    brand: "Don Julio",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Cooked agave, vanilla, caramel, oak",
    palate: "Cooked agave, pepper, vanilla, caramel",
    appearance: "Golden",
    how_to_enjoy: "Best for cocktails, especially Old Fashioneds",
  },
  {
    brand: "Don Julio",
    name: "Anejo",
    origin: "Jalisco",
    style: "Anejo",
    abv: "40%",
    aroma: "Vanilla, caramel, oak",
    palate: "Vanilla, butterscotch, butter",
    appearance: "Light amber",
    how_to_enjoy: "Neat, sipped",
  },
  {
    brand: "Don Julio",
    name: "1942",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: "40%",
    aroma: "Sweet, fruit, brown sugar, wet oak",
    palate: "Vanilla, agave, clove",
    appearance: "Golden",
    how_to_enjoy:
      "Neat or on the rocks. Also with red meats such as steak and any dessert that features chocolate.",
  },
  {
    brand: "Don Fulano",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40-50%",
    aroma: "Crisp agave, citrus and herbal notes",
    palate: "Sweet agave, hints of pepper and floral undertones",
    appearance: "Clear",
    how_to_enjoy:
      "Perfect for those who appreciate the pure and unadulterated flavors of agave.",
  },
  {
    brand: "El Tesoro",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Earthy agave, floral and herbal scents",
    palate: "Sweet agave, citrus and peppery notes",
    appearance: "Clear",
    how_to_enjoy: "Spicy margarita or paloma to enhance notes of pepper",
  },
  {
    brand: "Espolon",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Cooked agave, fruity and slight floral hints",
    palate: "Agave sweetness, tropical fruit and gentle spice",
    appearance: "Clear",
    how_to_enjoy: "Ranch water to balance the saltiness",
  },
  {
    brand: "Espolon",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Agave, vanilla and caramel notes with a touch of oak",
    palate: "Smooth agave, butterscotch, and toasted oak flavors",
    appearance: "Pale gold",
    how_to_enjoy: "Old fashioneds or sipping neat",
  },
  {
    brand: "Fortaleza",
    name: "Reposado Single Barrel",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "47.4%",
    aroma: "Cooked agave, prominent oak, astringency, caramelized apricots",
    palate: "Deep roasted agave, vanilla, fresh herbs, black pepper, cedar",
    appearance: "Slightly darker golden than traditional reposado",
    how_to_enjoy: "As a sipper",
  },
  {
    brand: "Fortaleza",
    name: "Winter Blend",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "43.5%",
    aroma: "Aroma of vanilla, caramel, oak, citrus, cinnamon",
    palate:
      "Smooth and full-bodied, dark chocolate, honey, roasted nuts, long and warming finish",
    appearance: "Golden yellow",
    how_to_enjoy: "Sipped or in an Old Fashioned",
  },

  {
    brand: "G4",
    name: "Blanco",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma: "Cooked agave, herbal, vegetal notes",
    palate: "Black pepper, butter, smoke",
  },
  {
    brand: "G4",
    name: "Reposado",
    origin: "Jesus Maria, Jalisco",
    abv: "40%",
    aroma: "Vanilla, black pepper, cinnamon, grass",
    palate: "Oak, caramel, citrus, butter",
  },
  {
    brand: "Grand Mayan",
    name: "Extra Anejo",
    origin: "Amtaitan, Jalisco, MX",
    abv: "40%",
    aroma: "Sweet toasted oak, caramel, vanilla, cooked agave",
    palate:
      "Sweet toasted oak, caramel, vanilla, dark chocolate, mascarpone, butterscotch, cream",
  },
  {
    brand: "Herradura",
    name: "Silver",
    origin: "Jalisco",
    abv: "40%",
    aroma:
      "Olive brine, tapenade, musty cucumber, bell pepper, vanilla, cotton candy",
    palate:
      "Cerignola olives, dried oregano, vanilla, candied citrus peels, pickled jalapeños, asparagus",
  },
  {
    brand: "Herradura",
    name: "Reposado",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma: "Agave, vanilla, caramel, orange",
    palate: "Agave, vanilla, oak, spice",
  },
  {
    brand: "Herradura",
    name: "Anejo",
    origin: "Jalisco, Mexico (Los Valles)",
    abv: "40%",
    aroma: "Oak, caramel, vanilla, honey, butterscotch",
    palate: "Cinnamon, candied walnuts, buttery, slightly peppery",
  },
  {
    brand: "Herradura",
    name: "Ultra Anejo",
    origin: "Jalisco, MX",
    abv: "35-39%",
    aroma: "Vanilla, agave, caramel",
    palate: "Heavy coconut and vanilla flavor with subtle caramel",
  },
  {
    brand: "Jose Cuervo",
    name: "Reserva Blanco",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma:
      "Light aroma with grass and jackfruit, lime, salt, and sweet peppers",
    palate:
      "Mild flavor with accents of key lime pie, vanilla citrus cream, baked prickly pear cactus, and bubblegum",
  },
  {
    brand: "Jose Cuervo",
    name: "Reserva de la Familia",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma: "Zesty, dill, fennel, pepper",
    palate: "Semisweet, caramel, vanilla, marzipan",
  },
  {
    brand: "La Gritona",
    name: "Reposado",
    origin: "Jalisco, Mexico (Los Altos)",
    abv: "40%",
    aroma: "Vegetal, light minerals, grass, citrus",
    palate: "Raw agave, touch of vanilla and oak, slight white pepper",
  },
  {
    brand: "Maestro Dobel",
    name: "Atelier",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma: "",
    palate: "",
  },
  {
    brand: "Maestro Dobel",
    name: "Diamante",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma: "Vanilla, pepper, citrus, oak",
    palate: "Caramel, honey, maple, vanilla",
  },
  {
    brand: "Maestro Dobel",
    name: "Humito",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma: "Smoke, agave, black pepper, earth, vegetal",
    palate: "Smoke, tobacco, charcoal, wet earth",
  },
  {
    brand: "Maestro Dobel",
    name: "Silver",
    origin: "Jalisco, Mexico (Los Valles)",
    abv: "40%",
    aroma: "Buttery caramel, olives, and dried fruit scent",
    palate:
      "Range from caramel, honey, and maple to nutty with notes of vanilla",
  },
  {
    brand: "Maestro Dobel",
    name: "Reposado",
    origin: "Jalisco",
    abv: "40%",
    aroma:
      "Buttery caramel and fruity notes, with touches of cinnamon and almond, with a slight hint of smokiness from toasted wood.",
    palate:
      "A mix of sweet, nutty, and vanilla flavors with indescribable smoothness and a long finish",
  },
  {
    brand: "Maestro Dobel",
    name: "Anejo",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma:
      "Buttery caramel, almond and cinnamon notes, pineapple and apple with a slight smokiness",
    palate:
      "Wood interspersed with sweet, nutty and vanilla flavors, with slight notes of agave and fruitiness. It has an indescribably smooth, long finish",
  },
  {
    brand: "Milagro",
    name: "Select Barrel Silver",
    origin: "Jalisco, MX",
    abv: "40%",
    aroma: "Crisp, fresh, agave-forward",
    palate:
      "Crisp, fresh, agave-forward with vanilla notes and a spicy, dry finish",
  },
  {
    brand: "Milagro",
    name: "Select Barrel Reposado",
    origin: "Jalisco",
    abv: "40%",
    aroma: "Golden honey, buttery smooth",
    palate:
      "The taste is clean, vanilla, with white pepper and cinnamon spices and a dry finish",
  },
  {
    brand: "Milagro",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: "40%",
    aroma: "Oak, orange, toasted coconut",
    palate: "Agave, stone fruit, butterscotch",
    appearance: "Light amber with golden hues",
    how_to_enjoy:
      "Affordable Anejo makes this spirit a great opportunity to try it in many different ways",
  },
  {
    brand: "Mijenta",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Cooked agave, citrus, pepper, flowers",
    palate: "Cooked agave, pepper, citrus, butter",
    appearance: "Clear",
    how_to_enjoy:
      "Great in a margarita, paloma or on the rocks. High quality tequila",
  },
  {
    brand: "Mijenta",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Cooked agave, oak, vanilla, banana",
    palate: "Cooked agave, pepper, oak, banana",
    appearance: "Slight amber color",
    how_to_enjoy:
      "Use this tequila to replace any whiskey for a different take on classic cocktails like Old Fashioneds",
  },
  {
    brand: "Patron",
    name: "Silver",
    origin: "Jalisco, MX",
    style: "Silver",
    abv: "40%",
    aroma: "Fruits & citrus",
    palate: "Smooth & sweet with a light pepper finish",
    appearance: "Clear",
    how_to_enjoy:
      "The citrus notes in this tequila will do wonderful in a fruit based cocktail, such as a paloma.",
  },
  {
    brand: "Patron",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Oak & fresh agave",
    palate: "Fresh agave, oak, citrus, fruit, honey",
    appearance: "Light amber tint",
    how_to_enjoy:
      "Due to Patrón Reposado having a hint of oak flavor it has a lot of variation for ways to enjoy from sipping over a large cube to in an old fashion, this reposado has a wide range of options.",
  },
  {
    brand: "Patron",
    name: "Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: "40%",
    aroma: "Oak wood, vanilla, and raisins.",
    palate:
      "Oak wood with notes of vanilla, raisin, and honey with a caramel and smoky finish.",
    appearance: "Warm amber",
    how_to_enjoy:
      "It is recommended to sip this Añejo neat or over a large cube. With the lingering oak flavor Patrón Añejo would also be a wonderful star of the show in a manhattan or sazerac.",
  },
  {
    brand: "Patron",
    name: "Roca Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "42%",
    aroma: "Cooked agave, oak. vanilla, caramel",
    palate: "Black pepper, whiskey, cinnamon, wood",
    appearance: "Light golden",
    how_to_enjoy: "Neat or large cube",
  },
  {
    brand: "Siembre Azul",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Citrus, cooked agave, pepper",
    palate: "Fruity notes, cracked pepper",
    appearance: "Clear",
    how_to_enjoy: "Great in cocktails",
  },
  {
    brand: "Siembre Valles",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Citrus, caramel, vanilla",
    palate: "Vanilla, oak, mellow agave",
    appearance: "Clear",
    how_to_enjoy: "Neat or on the rocks, Old Fashioned",
  },
  {
    brand: "Siete Leguas",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Black pepper, earth, vegetal",
    palate: "Crisp, bright, citrus, peppery",
    appearance: "Clear",
    how_to_enjoy: "Classic tequila cocktails like margarita or paloma",
  },
  {
    brand: "Siete Leguas",
    name: "Reposado",
    origin: "Jalisco",
    style: "Reposado",
    abv: "40%",
    aroma: "Agave, oak, citrus",
    palate: "Slight sweetness, vanilla, caramel",
    appearance: "Golden",
    how_to_enjoy:
      "Neat or on the rocks, adds depth to cocktails like an Old Fashioned or sunrise",
  },
  {
    brand: "Siete Leguas",
    name: "Anejo",
    origin: "Jalisco",
    style: "Anejo",
    abv: "40-43%",
    aroma: "Agave, oak, vanilla",
    palate: "Caramel, vanilla, toasted oak",
    appearance: "Golden",
    how_to_enjoy:
      "Siete Leguas Añejo is ideal for sipping slowly to appreciate its sophisticated flavor profile. It also pairs well with desserts and makes an excellent after-dinner drink.",
  },
  {
    brand: "Suerte",
    name: "Silver",
    origin: "Los Altos, Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Cooked agave, citrus, vegetal, black pepper",
    palate: "Sweet and vegetal notes, cooked agave",
    appearance: "Clear",
    how_to_enjoy: "Margarita, on the rocks or any mixed cocktail",
  },
  {
    brand: "Suerte",
    name: "Reposado",
    origin: "Los Altos, Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Vanilla, cooked agave, caramel, citrus",
    palate: "Oak, black pepper, earth, cinnamon",
    appearance: "Pale golden",
    how_to_enjoy: "Sipped in a mixed drink",
  },
  {
    brand: "Suerte",
    name: "Anejo",
    origin: "Los Altos, Jalisco, MX",
    style: "Anejo",
    abv: "40%",
    aroma: "Oak, vanilla, caramel, fruity, butterscotch, earthy",
    palate: "Oak, cooked agave, butter, caramel, apple, baking spice.",
    appearance: "Amber/caramel",
    how_to_enjoy:
      "Sipped neat or with a large cube, would not recommend in a mixed cocktail",
  },
  {
    brand: "Tapatio",
    name: "Blanco",
    origin: "Jalisco, MX",
    style: "Blanco",
    abv: "40%",
    aroma: "Herbal, earthy, vegetal",
    palate: "Agave, peppery, grassy, citrus, blast of cinnamon",
    appearance: "Clear, silver tones",
    how_to_enjoy:
      "Specially designed to be used in cocktails such as a ranch water but can also be sipped on the rocks for a smooth indulgence",
  },
  {
    brand: "Tequila Ocho",
    name: "Plata",
    origin: "Jalisco, Mexico (Highlands of Arandas)",
    style: "Blanco",
    abv: "40%",
    aroma: "Crisp, bright agave, herbal",
    palate: "Full agave, fresh cut grass, earthiness",
    appearance: "Clear",
    how_to_enjoy:
      "Great in Margaritas and other cocktails but so buttery smooth can be perfect for sipping on the rocks with a lime or orange slice and a dash of agave.",
  },
  {
    brand: "Tequila Ocho",
    name: "Reposado",
    origin: "Jalisco, MX",
    style: "Reposado",
    abv: "40%",
    aroma: "Cooked agave, vanilla, butterscotch/caramel, oaky",
    palate: "Nuts, orange, spices, sweet, clove",
    appearance: "Translucent amber",
    how_to_enjoy:
      "Best to be sipped slowly neat or on the rocks but also blends well in cocktails such as a tequila sunrise",
  },
  {
    brand: "Tequila Ocho",
    name: "Anejo",
    origin: "Jalisco, Mexico",
    style: "Anejo",
    abv: "40%",
    aroma: "Floral, mild, light chocolate, agave",
    palate: "Honey, butter, cooked agave, vanilla",
    appearance: "Yellow/golden",
    how_to_enjoy: "Neat or in an Old Fashioned",
  },
  {
    brand: "Tequila Ocho",
    name: "Extra Anejo",
    origin: "Jalisco, MX",
    style: "Anejo",
    abv: "40%",
    aroma: "Agave, vanilla, oak, caramel",
    palate: "Agave, oak, vanilla, citrus",
    appearance: "Light golden",
    how_to_enjoy: "Neat or over a large cube",
  },
  {
    brand: "Tromba",
    name: "Blanco",
    origin: "Jalisco, Mexico",
    style: "Blanco",
    abv: "40%",
    aroma: "Sweet, citrus, agave",
    palate: "Herbal, citrus, caramelized agave, lime, honey",
    appearance: "Clear",
    how_to_enjoy: "Cocktails like margarita, ranch water, paloma",
  },
  {
    brand: "Tromba",
    name: "Reposado",
    origin: "Jalisco, Mexico",
    style: "Reposado",
    abv: "40%",
    aroma: "Roasted walnut, smoked wood, cocoa",
    palate: "Chocolate, brown sugar, nuts",
    appearance: "Yellow/golden",
    how_to_enjoy: "On the rocks",
  },
];

const seedTequilas = () => Tequila.bulkCreate(tequilaData);

module.exports = seedTequilas;
